### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by lazywhite** [AngularShowcase/angular2-seed-ng2-highcharts#13]
```
[yargs@^3.32.0] existed at /Users/white/angular2-seed-ng2-highcharts/node_modules/yargs
Error: angular2@2.0.0-beta.6 sha1:f098972797a9ce64136fcc249b366799064c9aac not equal to 8e47d91e146a5b70c5f71483301727a1163d38ef (angular2@2.0.0-beta.6)
Error: angular2@2.0.0-beta.6 sha1:f098972797a9ce64136fcc249b366799064c9aac not equal to 8e47d91e146a5b70c5f71483301727a1163d38ef (angular2@2.0.0-beta.6)
    at ReadStream.readstream.on (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:220:24)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
$ node -v
v6.0.0
```

**Comment by Bigous** [comment]
It seams you have a cache problem... yet, the version of this repo (angular2@2.0.0-beta.6) doesn't supports node 6... I'll upgrade this soon...

**Comment by ghost** [comment]
@Bigous  
Thank you for providing this valuable enhancement for the angular2-seed. 
I'm underway with node v6.5.0 --> works fine --> I think this issue can be closed.
